-- CreateTable
CREATE TABLE "Events" (
    "eventID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "title" TEXT NOT NULL,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ubication" TEXT NOT NULL,
    "description" TEXT NOT NULL
);
